export const theme = {
  colors: {
    primary: "#2E7D32",       // forest green
    primaryLight: "#4CAF50",
    primaryDark: "#1B5E20",
    secondary: "#FF8F00",     // amber
    secondaryLight: "#FFB300",
    background: "#F9FBF7",
    surface: "#FFFFFF",
    error: "#D32F2F",
    success: "#388E3C",
    warning: "#F57C00",
    textPrimary: "#1A1A1A",
    textSecondary: "#555555",
    textMuted: "#888888",
    border: "#E0E0E0",
    card: "#FFFFFF",
    tabBar: "#FFFFFF",
    tabBarActive: "#2E7D32",
    tabBarInactive: "#9E9E9E",
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  borderRadius: {
    sm: 6,
    md: 12,
    lg: 20,
    full: 999,
  },
  fontSize: {
    xs: 11,
    sm: 13,
    md: 15,
    lg: 18,
    xl: 22,
    xxl: 28,
    hero: 36,
  },
  fontWeight: {
    regular: "400" as const,
    medium: "500" as const,
    semibold: "600" as const,
    bold: "700" as const,
    extrabold: "800" as const,
  },
  shadow: {
    sm: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.08,
      shadowRadius: 4,
      elevation: 2,
    },
    md: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.12,
      shadowRadius: 8,
      elevation: 4,
    },
    lg: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.16,
      shadowRadius: 16,
      elevation: 8,
    },
  },
};
